### ISSUE TITLE
nbs-irc options window issue since mIRC 7.51

### ISSUE THREAD

**Issue by delixyr** [ElectronicWar/nbs-irc#15]
![mirc_2017-09-30_09-09-29](https://user-images.githubusercontent.com/4602841/31042176-85159a90-a5bf-11e7-856b-31948d79ebae.png)

Since updating mIRC to 7.51 the options window appears so.

**Comment by ElectronicWar** [comment]
Not sure what went wrong for you, I have no issue like that.

![image](https://user-images.githubusercontent.com/1890874/31045570-09eb81d6-a5e7-11e7-858c-53843457d49b.png)

**Comment by delixyr** [comment]
I retarted nbs again. Stll that showed. Removed nbs and installed again. Now it works. The same solution worked for the issue I had reported before too. :)
Maybe its some issue with my installation.

**Comment by ElectronicWar** [comment]
Not sure what can cause that, I have the same installation running for months now and no issues when updating mIRC itself. If you can find something out let me know, I will close this for now.
