### ISSUE TITLE
/mem displays incorrect MB

### ISSUE THREAD

**Issue by Kebabpizza** [ElectronicWar/nbs-irc#16]
[19:21:43] <H4ndy> memory usage: 1/2048 MB (48%)
    [19:22:10] <Rotab> memory usage: 1/2048 MB (56%)

The percentage seems correct, but 1/2048 is not.

**Comment by ElectronicWar** [comment]
Function relies on a 3rd party DLL that isn't maintained for years. Can't be fixed without replacing the library.
