### ISSUE TITLE
Channel Notice timestamp from ZNC log.

### ISSUE THREAD

**Issue by DozerKitty** [ElectronicWar/nbs-irc#2]
The latest update, and subsequent PM fix (:D), was really nice, but I noticed that channel notice from ZNC log is still behaving like the chat did before, with timestamps being current time on them all, and not when they were sent out. 

Is this something you can look into?

**Comment by ElectronicWar** [comment]
Thanks for the report, I will try to replicate the issue for a fix

**Comment by ElectronicWar** [comment]
I think I have found the issue, I will provide a fix in the next 1-2 days.

**Comment by ElectronicWar** [comment]
@DozerKitty Could you test my changes? I rarely get any notices so I require some help if it works properly. Please use the "Download Zip" function on the main Github pages or download the latest main.nbs directly from the repository, thanks!
