### ISSUE TITLE
Whois opens 2 windows, and puts (1) in front of every line.

### ISSUE THREAD

**Issue by DozerKitty** [ElectronicWar/nbs-irc#3]
Second window doesn't show anything though, but it still opens.

(1) [whois: H4ndy|off](1)   name: H4ndy
(1)   address: H4ndy@H4ndy.users.quakenet.org
(1)   channels: #help.script @#x0r #nbs-irc #PhantomL0rd @#lolgents (5)
(1)   auth: H4ndy
(1)   server: *.quakenet.org (QuakeNet IRC Server)
(1)   idle: 18h 59m 6s, signed on: 03:15:03 - 29/07/2015 (18h 59m 17s ago)
(1) [/whois: 22:14](1)

**Comment by DozerKitty** [comment]
Also noted, when connected to more than one server, all whois requests will go to the first network a whois request was made. The whois window will still open on the other networks, but only display empty chat, and 2 whois windows will be open on the first network, with one being empty.

**Comment by ElectronicWar** [comment]
Fixed with 7e952ca
