### ISSUE TITLE
Alias vote - main.nbs - L1185

### ISSUE THREAD

**Issue by ghost** [ElectronicWar/nbs-irc#7]
1) There's a small bug when you run the `/vote` command and you are not connected.

Before and after fix:
![image](https://cloud.githubusercontent.com/assets/13683523/17465064/31e3d20e-5ced-11e6-92a5-7d8cd77e81f9.png)

Code:
`if (!$server) { n.echo -atg info not connected | return }`
Ought to be:
`if (!$server) { n.echo info -atg not connected | return }` 

2) If you start a vote, it'll ask for a yes/no question. If you just click the OK button it shouldn't continue with the vote, it should just return / halt.

Code:
`set %vote $n.input(Enter topic (yes/no))` 
Ought to be:
`set %vote $$n.input(Enter topic (yes/no))`

**Comment by ElectronicWar** [comment]
Fixed with 19de905
